### PR TITLE
JavaScript Capstone 💠

### PR DESCRIPTION
**Pull request by rmrmrmr**
### On this pull request you will find and awesome Marvel Movies page.

- We retrieved all of the movies from this [API](https://www.tvmaze.com/api)
- We rendered the movies on the homepage. By default, we set the background of the page to the poster of the first movie, but when you click on another one, the background is updated!
- We also added some basic information of the selected movie to be displayed at the left of the homepage. It also updates itself depending on which movie you have selected.
- We added likes for each movie. The information is stored on the [Involvement API](https://www.notion.so/Involvement-API-869e60b5ad104603aa6db59e08150270). Each time a user likes a movie, the information is sent to the API and then it is retrieved again so the number of likes displayed is always up to date.
- We added a popup for the users to add comments. They are also stored on the involvement API so every user can see all of the comments that have been added. 
- We added a reservation popup so users can reserve the movies and they can see when other users have done so. The information for each movie is also stored on the Involvement API.
-Here you can watch the [Live Demo](https://rmrmrmr.github.io/JavaScript-Capstone/dist/)!
- Here you can watch a [video](https://www.loom.com/share/d1ccbbc41f574beebc43762ac1440d71) of us showing the functionality of the page

### CODE REVIEW

**Review by MaganaAsiati — CHANGES_REQUESTED** [review]
# STATUS: Required Changes ♻️♻️♻️ 

Hi @rmrmrmr

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

AlonzoLeroneThisCloseGIF

## Highlights
✅ No linter error
✅ README is professional

## Required Changes ♻️

- [ ] Your project looks nice but make sure to work on the accessibility of the  reservation section. you use a color that is not visible when I try to add a reservation  I'm not able to see what I'm writing kindly fix that and make sure the reversion implementation working perfectly :+1: 

image

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by vvoo21** [comment]
Thanks, @MaganaAsiati . The changes have been made :)

**Review by MaganaAsiati — APPROVED** [review]
# Status: Approved [✔️](https://emojipedia.org/check-mark/)
## Hi @rmrmrmr  , I'm @MaganaAsiati , your reviewer for this PR  :wave: 
Great work on making the changes requested by a previous reviewer 👏 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 





## Highlights
- Descriptive pull request :heavy_check_mark:👨🏻‍💻
- Descriptive README file  :heavy_check_mark:👨🏻‍💻
- Great work using the right GitHub Flow.:heavy_check_mark:
- No Linter errors :heavy_check_mark:


## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] [OPTIONAL] Please make sure to make your commit messages more descriptive in the future.
- [ ] Check the comments under the review.



Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
Cheers and Happy coding! 🤓 👏👏👏

**Comment by vvoo21** [comment]
@MaganaAsiati 😃

**Pull request merged**
